services:
  postgres:
    image: postgres:16-alpine
    container_name: yame_postgres
    restart: always
    environment:
      POSTGRES_DB: yame_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  backend-service:
    container_name: backend-service
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yame_backend
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - default

networks:
  default:
    name: backend-service

volumes:
  postgres_data:
