spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/yame_backend
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    repair-on-migrate: true
  sql:
    init:
      mode: never
  # Cấu hình upload file size
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  access-expiry: 1d
  refresh-expiry: 14d
  reset-expiry: 60m

  secretKey: 93706878cb8f89019621b0067e944224d311b5e6d0635f0230001e07c2c73b1c
  refreshKey: SN4n2ahiSXMlt2y7JSXcE8sNDTFm3hhyDBtFIYlt68w=
  resetKey: fYk/hel7E8o/QT/6vQIfbKfeMMt2ggCNIaHc2iiwdNI=

cloudinary:
  cloud-name: daypiprgr
  api-key: 888232376992765
  api-secret: 17mB4yTK7rPwfq4c5bMtHo8D_28
